import {
    Aura_Gold,
    Aura_Silver,
    Dryad_Gold,
    Dryad_Silver,
    Gnome_Gold,
    Gnome_Silver,
    Jinn_Gold,
    Jinn_Silver,
    Sala_Gold,
    Sala_Silver,
    Shade_Gold,
    Shade_Silver,
    Undine_Gold,
    Undine_Silver,
    Wisp_Gold,
    Wisp_Silver
} from "@/forge/items/coins"
import {
    All_Meat,
    Applesocks,
    Apricat,
    Bellgrapes,
    Boarmelon,
    Bumpkin,
    Cabadillo,
    Cherry_Bombs,
    Citrisquid,
    Conchurnip,
    Cornflower,
    Dialaurel,
    Diceberry,
    Fishy_Fruit,
    Garlicrown,
    Gold_Clover,
    Heart_Mint,
    Honey_Onion,
    Lilipods,
    Loquat_Shoes,
    Mangoelephant,
    Masked_Potato,
    Mush_In_A_Box,
    Needlettuce,
    Orangeopus,
    Orcaplant,
    Peach_Puppy,
    Pear_Oheels,
    Pine_Oclock,
    Rhinoloupe,
    Rocket_Papaya,
    Spade_Basil,
    Spiny_Carrot,
    Springanana, Squalphin, Sweet_Moai, Toadstoolshed, Whalamato
} from "@/forge/items/produce";
import {Angel_Feather, Clear_Feather, Flaming_Quill, Moth_Wing, Raven_Feather} from "@/forge/items/wings_feathers";
import {
    Angry_Eye,
    Blank_Eye,
    Creepy_Eye,
    Dangerous_Eye,
    Little_Eye,
    Silly_Eye,
    Sleepy_Eye,
    Wicked_Eye
} from "@/forge/items/eyes";
import {
    Big_Seed,
    Crooked_Seed,
    Flat_Seed,
    Long_Seed,
    Oblong_Seed,
    Round_Seed,
    Small_Seed,
    Spiny_Seed
} from "@/forge/items/seeds";
import {
    Chaos_Crystal,
    Earth_Stone,
    Fire_Stone,
    Glow_Crystal,
    Moon_Crystal,
    Sun_Crystal, Water_Stone, Wind_Stone
} from "@/forge/items/stones_crystals";
import {
    Giants_Horn,
    Healing_Claw,
    Poison_Fang,
    Scissors,
    Sharp_Claw,
    Vampire_Fang,
    Zombie_Claw
} from "@/forge/items/fangs_claws";
import {No_Item} from "@/forge/items/No_Item";
import {White_Feather} from "@/forge/items/wings_feathers/White_Feather";
import {Acid, Aroma_Oil, Ether, Holy_Water} from "@/forge/items/bottles";
import {Dragon_Blood} from "@/forge/items/bottles/Dragon_Blood";
import {Dragon_Breath, Ghosts_Howl, Mercury, Stinky_Breath, Virgins_Sigh} from "@/forge/items/vials";
import {Electricity} from "@/forge/items/urns/Electricity";
import {Ear_Of_Wheat, Moss} from "@/forge/items/urns";
import {Baked_Roach, Blackened_Bat} from "@/forge/items/pellets";
import {Greenball_Bun, Tako_Bug} from "@/forge/items/other";
import {Ash, Grave_Dirt, Knockout_Dust, Poison_Powder, Rust, Sleepy_Powder, Sulpher} from "@/forge/items/powders";
import {Hairball, Messy_Scroll, Mirror_Piece, Needle, Wad_Of_Wool} from "@/forge/items/pouches";

const ITEM = Object.freeze(
    {
        NoItem: new No_Item(),
        WispGold: new Wisp_Gold(),
        ShadeGold: new Shade_Gold(),
        DryadGold: new Dryad_Gold(),
        AuraGold: new Aura_Gold(),
        SalaGold: new Sala_Gold(),
        GnomeGold: new Gnome_Gold(),
        JinnGold: new Jinn_Gold(),
        UndineGold: new Undine_Gold(),
        WispSilver: new Wisp_Silver(),
        ShadeSilver: new Shade_Silver(),
        DryadSilver: new Dryad_Silver(),
        AuraSilver: new Aura_Silver(),
        SalaSilver: new Sala_Silver(),
        GnomeSilver: new Gnome_Silver(),
        JinnSilver: new Jinn_Silver(),
        UndineSilver: new Undine_Silver(),
        FireStone: new Fire_Stone(),
        EarthStone: new Earth_Stone(),
        WindStone: new Wind_Stone(),
        WaterStone: new Water_Stone(),
        SunCrystal: new Sun_Crystal(),
        MoonCrystal: new Moon_Crystal(),
        GlowCrystal: new Glow_Crystal(),
        ChaosCrystal: new Chaos_Crystal(),
        RoundSeed: new Round_Seed(),
        OblongSeed: new Oblong_Seed(),
        CrookedSeed: new Crooked_Seed(),
        BigSeed: new Big_Seed(),
        SmallSeed: new Small_Seed(),
        LongSeed: new Long_Seed(),
        FlatSeed: new Flat_Seed(),
        SpinySeed: new Spiny_Seed(),
        Bellgrapes: new Bellgrapes(),
        Diceberry: new Diceberry(),
        Mangoelephant: new Mangoelephant(),
        LoquatShoes: new Loquat_Shoes(),
        PearOheels: new Pear_Oheels(),
        Squalphin: new Squalphin(),
        Citrisquid: new Citrisquid(),
        Springanana: new Springanana(),
        PeachPuppy: new Peach_Puppy(),
        Apricat: new Apricat(),
        Applesocks: new Applesocks(),
        Whalamato: new Whalamato(),
        PineOclock: new Pine_Oclock(),
        FishyFruit: new Fishy_Fruit(),
        Boarmelon: new Boarmelon(),
        Rhinoloupe: new Rhinoloupe(),
        Orcaplant: new Orcaplant(),
        Garlicrown: new Garlicrown(),
        HoneyOnion: new Honey_Onion(),
        SweetMoai: new Sweet_Moai(),
        SpinyCarrot: new Spiny_Carrot(),
        Conchurnip: new Conchurnip(),
        Cornflower: new Cornflower(),
        Cabadillo: new Cabadillo(),
        Needlettuce: new Needlettuce(),
        CherryBombs: new Cherry_Bombs(),
        MaskedPotato: new Masked_Potato(),
        Lilipods: new Lilipods(),
        RocketPapaya: new Rocket_Papaya(),
        Orangeopus: new Orangeopus(),
        Bumpkin: new Bumpkin(),
        HeartMint: new Heart_Mint(),
        SpadeBasil: new Spade_Basil(),
        Dialaurel: new Dialaurel(),
        GoldClover: new Gold_Clover(),
        MushInABox: new Mush_In_A_Box(),
        Toadstoolshed: new Toadstoolshed(),
        AllMeat: new All_Meat(),
        SharpClaw: new Sharp_Claw(),
        PoisonFang: new Poison_Fang(),
        GiantsHorn: new Giants_Horn(),
        Scissors: new Scissors(),
        HealingClaw: new Healing_Claw(),
        ZombieClaw: new Zombie_Claw(),
        VampireFang: new Vampire_Fang(),
        LittleEye: new Little_Eye(),
        SleepyEye: new Sleepy_Eye(),
        SillyEye: new Silly_Eye(),
        DangerousEye: new Dangerous_Eye(),
        AngryEye: new Angry_Eye(),
        BlankEye: new Blank_Eye(),
        WickedEye: new Wicked_Eye(),
        CreepyEye: new Creepy_Eye(),
        AngelFeather: new Angel_Feather(),
        RavenFeather: new Raven_Feather(),
        ClearFeather: new Clear_Feather(),
        MothWing: new Moth_Wing(),
        FlamingQuill: new Flaming_Quill(),
        WhiteFeather: new White_Feather(),
        AromaOil: new Aroma_Oil(),
        DragonBlood: new Dragon_Blood(),
        Acid: new Acid(),
        HolyWater: new Holy_Water(),
        Ether: new Ether(),
        Mercury: new Mercury(),
        StinkyBreath: new Stinky_Breath(),
        GhostsHowl: new Ghosts_Howl(),
        DragonBreath: new Dragon_Breath(),
        VirginsSigh: new Virgins_Sigh(),
        Electricity: new Electricity(),
        Moss: new Moss(),
        EarOfWheat: new Ear_Of_Wheat(),
        BakedRoach: new Baked_Roach(),
        BlackenedBat: new Blackened_Bat(),
        Sulpher: new Sulpher(),
        PoisonPowder: new Poison_Powder(),
        SleepyPowder: new Sleepy_Powder(),
        KnockoutDust: new Knockout_Dust(),
        Rust: new Rust(),
        GraveDirt: new Grave_Dirt(),
        Ash: new Ash(),
        Hairball: new Hairball(),
        Needle: new Needle(),
        MirrorPiece: new Mirror_Piece(),
        WadOfWool: new Wad_Of_Wool(),
        MessyScroll: new Messy_Scroll(),
        GreenballBun: new Greenball_Bun(),
        TakoBug: new Tako_Bug()
    }
)
export {ITEM};
