import {
    Acid,
    All_Meat,
    Angel_Feather,
    Angry_Eye,
    Applesocks,
    Apricat,
    Aroma_Oil,
    Ash,
    Baked_Roach,
    Bellgrapes,
    Big_Seed,
    Blackened_Bat,
    Blank_Eye,
    Boarmelon,
    Bumpkin,
    Cabadillo,
    Chaos_Crystal,
    Cherry_Bombs,
    Citrisquid,
    Clear_Feather,
    Conchurnip,
    Cornflower,
    Creepy_Eye,
    Crooked_Seed,
    Dangerous_Eye,
    Dialaurel,
    Diceberry,
    Dragon_Blood,
    Dragons_Breath,
    Ear_Of_Wheat,
    Earth_Stone,
    Electricity,
    Ether,
    Fire_Stone,
    Fishy_Fruit,
    Flaming_Quill,
    Flat_Seed,
    Garlicrown,
    Ghosts_Howl,
    Giants_Horn,
    Glow_Crystal,
    Gold_Clover,
    Grave_Dirt,
    Greenball_Bun,
    Hairball,
    Healing_Claw,
    Heart_Mint,
    Holy_Water,
    Honey_Onion,
    Knockout_Dust,
    Lilipods,
    Little_Eye,
    Long_Seed,
    Loquat_Shoes,
    Mangoelephant,
    Masked_Potato,
    Mercury,
    Messy_Scroll,
    Mirror_Piece,
    Moon_Crystal,
    Moss,
    Moth_Wing,
    Mush_In_A_Box,
    Needle,
    Needlettuce,
    No_Item,
    Oblong_Seed,
    Orangeopus,
    Orcaplant,
    Peach_Puppy,
    Pear_Oheels,
    Pine_Oclock,
    Poison_Fang,
    Poison_Powder,
    Raven_Feather,
    Rhinoloupe,
    Rocket_Papaya,
    Round_Seed,
    Rust,
    Scissors,
    Sharp_Claw,
    Silly_Eye,
    Sleepy_Eye,
    Sleepy_Powder,
    Small_Seed,
    Spade_Basil,
    Spiny_Carrot,
    Spiny_Seed,
    Springanana,
    Squalphin,
    Stinky_Breath,
    Sulpher,
    Sun_Crystal,
    Sweet_Moai,
    Tako_Bug,
    Toadstoolshed,
    Vampire_Fang,
    Virgins_Sigh,
    Wad_Of_Wool,
    Water_Stone,
    Whalamato,
    White_Feather,
    Wicked_Eye,
    Wind_Stone,
    Zombie_Claw
} from "@/forge/items/index";

import {
    Wisp_Gold, Wisp_Silver,
    Shade_Gold, Shade_Silver,
    Dryad_Gold, Dryad_Silver,
    Aura_Gold, Aura_Silver,
    Sala_Gold, Sala_Silver,
    Gnome_Gold, Gnome_Silver,
    Jinn_Gold, Jinn_Silver,
    Undine_Gold, Undine_Silver
} from "@/forge/items/coins"

const item_list = [new No_Item(), new Wisp_Gold(),
    new Shade_Gold(), new Dryad_Gold(), new Aura_Gold(),
    new Sala_Gold(), new Gnome_Gold(), new Jinn_Gold(),
    new Undine_Gold(), new Wisp_Silver(), new Shade_Silver(),
    new Dryad_Silver(), new Aura_Silver(), new Sala_Silver(),
    new Gnome_Silver(), new Jinn_Silver(), new Undine_Silver(),
    new Fire_Stone(), new Earth_Stone(), new Wind_Stone(),
    new Water_Stone(), new Sun_Crystal(), new Moon_Crystal(),
    new Glow_Crystal(), new Chaos_Crystal(), new Round_Seed(),
    new Oblong_Seed(), new Crooked_Seed(), new Big_Seed(),
    new Small_Seed(), new Long_Seed(), new Flat_Seed(),
    new Spiny_Seed(), new Bellgrapes(), new Diceberry(),
    new Mangoelephant(), new Loquat_Shoes(), new Pear_Oheels(),
    new Squalphin(), new Citrisquid(), new Springanana(),
    new Peach_Puppy(), new Apricat(), new Applesocks(),
    new Whalamato(), new Pine_Oclock(), new Fishy_Fruit(),
    new Boarmelon(), new Rhinoloupe(), new Orcaplant(),
    new Garlicrown(), new Honey_Onion(), new Sweet_Moai(),
    new Spiny_Carrot(), new Conchurnip(), new Cornflower(),
    new Cabadillo(), new Needlettuce(), new Cherry_Bombs(),
    new Masked_Potato(), new Lilipods(), new Rocket_Papaya(),
    new Orangeopus(), new Bumpkin(), new Heart_Mint(),
    new Spade_Basil(), new Dialaurel(), new Gold_Clover(),
    new Mush_In_A_Box(), new Toadstoolshed(), new All_Meat(),
    new Sharp_Claw(), new Poison_Fang(), new Giants_Horn(),
    new Scissors(), new Healing_Claw(), new Zombie_Claw(),
    new Vampire_Fang(), new Little_Eye(), new Sleepy_Eye(),
    new Silly_Eye(), new Dangerous_Eye(), new Angry_Eye(),
    new Blank_Eye(), new Wicked_Eye(), new Creepy_Eye(),
    new Angel_Feather(), new Raven_Feather(), new Clear_Feather(),
    new Moth_Wing(), new Flaming_Quill(), new White_Feather(),
    new Aroma_Oil(), new Dragon_Blood(), new Acid(), new Holy_Water(),
    new Ether(), new Mercury(), new Stinky_Breath(), new Ghosts_Howl(),
    new Dragons_Breath(), new Virgins_Sigh(), new Electricity(),
    new Moss(), new Ear_Of_Wheat(), new Baked_Roach(),
    new Blackened_Bat(), new Sulpher(), new Poison_Powder(),
    new Sleepy_Powder(), new Knockout_Dust(), new Rust(),
    new Grave_Dirt(), new Ash(), new Hairball(), new Needle(),
    new Mirror_Piece(), new Wad_Of_Wool(), new Messy_Scroll(),
    new Greenball_Bun(), new Tako_Bug()];
export {item_list};
